---
services:
    backend:
        image: ghcr.io/cdot65/pan-os-upgrade-web-backend:1.0.4-beta
        command: ./start.sh
        volumes:
            - ./backend:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
          - POSTGRES_HOST=db
          - REDIS_HOST=redis
        env_file:
            - ./backend/.env

    frontend:
        image: ghcr.io/cdot65/pan-os-upgrade-web-frontend:1.0.4-beta
        ports:
          - "8080:80"
        depends_on:
          - backend
        environment:
          - API_URL=http://backend:8000

    db:
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        env_file:
            - ./backend/.env
        ports:
            - "5432:5432"

    redis:
        image: redis:7.0.5-alpine
        expose:
            - 6379

    worker:
        image: ghcr.io/cdot65/pan-os-upgrade-web-worker:1.0.4-beta
        command: celery -A django_project worker -l debug
        deploy:
            replicas: 2
        volumes:
            - ./backend:/code
        depends_on:
            - backend
            - redis
        env_file:
            - ./backend/.env

networks:
    app:
        driver: bridge

volumes:
    postgres_data:
