apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pan-os-upgrade-web.fullname" . }}-frontend
  namespace: {{ include "pan-os-upgrade-web.namespace" . }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "pan-os-upgrade-web.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "pan-os-upgrade-web.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://{{ include "pan-os-upgrade-web.fullname" . }}-backend:8000"