apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pan-os-upgrade-web.name" . }}-redis
  labels:
    {{- include "pan-os-upgrade-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  serviceName: {{ include "pan-os-upgrade-web.name" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "pan-os-upgrade-web.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        {{- include "pan-os-upgrade-web.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cache
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: 6379