apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pan-os-upgrade-web.fullname" . }}-worker
  labels:
    {{- include "pan-os-upgrade-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "pan-os-upgrade-web.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "pan-os-upgrade-web.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.worker.image }}
        command: ["celery", "-A", "django_project", "worker", "-l", "debug"]
        envFrom:
        - configMapRef:
            name: {{ include "pan-os-upgrade-web.fullname" . }}-backend-config